#############################################################################
# COSC2541 - Programming Techniques
# Semester 3 2012 Assignment #2
# Full Name        : EDIT HERE
# Student Number   : EDIT HERE
# Start up code provided by Christopher Hoobin, Xiaodong Li and Quang Tran
#############################################################################

# Delete this comment and insert your code here.
